site_name: <MODULE CODE> Labs # TODO: Insert module code here
site_url: https://stm32-fanclub.github.io/zensical-nus-template # TODO: Insert website URL here
theme:
  features:
    - content.footnote.tooltips
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: lucide/moon
        name: Switch to light mode
  font:
    text: Merriweather
  icon:
    annotation: material/information-variant-circle-outline

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
copyright:  <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://nus-cs2100de.github.io/labs">NUS CS2100DE Labs</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/nus-cs2100de">NUS CS2100DE Team</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>. Template designed by <a href="mailto:neil@neilbaner.net">Neil Banerjee</a>. </p> # TODO: Replace CC License with your own CC BY-NC-SA license. 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stm32-fanclub/zensical_nus_template # TODO: Insert URL to GitHub Repository here

    - icon: fontawesome/solid/envelope
      link: mailto:neil@nus.edu.sg # TODO: Insert appropriate person's email address here

nav:
  - Home: index.md
  - How to use this website: howto.md
  - Grading: grading.md
  - Preparing for labs:
    - Lab Prerequisites: prep/prerequisites.md
    # TODO: Add more instructions for preparatory work - e.g. set up environment, install software, prepare hardware etc.
  - Lab manuals: 
    # TODO: Add, remove, change as needed for manuals
    - Lab 1: manuals/lab_01/manual_01.md
    - Lab 2: manuals/lab_02/manual_02.md
    - Lab 3: manuals/lab_03/manual_03.md
    - Lab 4: manuals/lab_04/manual_04.md
plugins:
  - mkdocs-video:
      is_video: True
