site_name: EE3033 Labs
site_url: https://nus-ee3033.github.io/labs here
theme:
  features:
    - content.footnote.tooltips
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: lucide/moon
        name: Switch to light mode
  font:
    text: Merriweather
  icon:
    annotation: material/information-variant-circle-outline

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
copyright: <p> <a href="https://nus-ee3033.github.io/Labs">NUS EE3033 Labs</a> Â© 2026 by <a href="https://github.com/nus-ee3033">NUS EE3033 Team</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;">. Template designed by <a href="mailto:neil@neilbaner.net">Neil Banerjee</a>. </p> 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nus-ee3033/Labs 

    - icon: fontawesome/solid/envelope
      link: mailto:ni.qq@nus.edu.sg 

nav:
  - Home: index.md
  - How to use this website: howto.md
  - Grading: grading.md
  - Preparing for labs:
    - Lab Prerequisites: prep/prerequisites.md
    # TODO: Add more instructions for preparatory work - e.g. set up environment, install software, prepare hardware etc.
  - Lab manuals: 
    # TODO: Add, remove, change as needed for manuals
    - Lab 1: manuals/lab_01/manual_01.md
    - Lab 2: manuals/lab_02/manual_02.md
    - Lab 3: manuals/lab_03/manual_03.md
    - Lab 4: manuals/lab_04/manual_04.md
    - Lab 5: manuals/lab_05/manual_05.md
    - Lab 6: manuals/lab_06/manual_06.md
    - Project: manuals/project/project.md
    # - Template: manuals/template/template.md
plugins:
  - mkdocs-video:
      is_video: True
